/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.6 at Mon Nov  2 16:32:49 2020. */

#ifndef PB_VECTOR_TILE_VECTOR_TILE_PB_H_INCLUDED
#define PB_VECTOR_TILE_VECTOR_TILE_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _vector_tile_Tile_GeomType {
    vector_tile_Tile_GeomType_UNKNOWN = 0,
    vector_tile_Tile_GeomType_POINT = 1,
    vector_tile_Tile_GeomType_LINESTRING = 2,
    vector_tile_Tile_GeomType_POLYGON = 3
} vector_tile_Tile_GeomType;
#define _vector_tile_Tile_GeomType_MIN vector_tile_Tile_GeomType_UNKNOWN
#define _vector_tile_Tile_GeomType_MAX vector_tile_Tile_GeomType_POLYGON
#define _vector_tile_Tile_GeomType_ARRAYSIZE ((vector_tile_Tile_GeomType)(vector_tile_Tile_GeomType_POLYGON+1))

/* Struct definitions */
typedef struct _vector_tile_Tile {
    pb_callback_t layers;
    pb_extension_t *extensions;
/* @@protoc_insertion_point(struct:vector_tile_Tile) */
} vector_tile_Tile;

typedef struct _vector_tile_Tile_Feature {
    bool has_id;
    uint64_t id;
    pb_callback_t tags;
    bool has_type;
    vector_tile_Tile_GeomType type;
    pb_callback_t geometry;
/* @@protoc_insertion_point(struct:vector_tile_Tile_Feature) */
} vector_tile_Tile_Feature;

typedef struct _vector_tile_Tile_Layer {
    pb_callback_t name;
    pb_callback_t features;
    pb_callback_t keys;
    pb_callback_t values;
    bool has_extent;
    uint32_t extent;
    uint32_t version;
    pb_extension_t *extensions;
/* @@protoc_insertion_point(struct:vector_tile_Tile_Layer) */
} vector_tile_Tile_Layer;

typedef struct _vector_tile_Tile_Value {
    pb_callback_t string_value;
    bool has_float_value;
    float float_value;
    bool has_double_value;
    double double_value;
    bool has_int_value;
    int64_t int_value;
    bool has_uint_value;
    uint64_t uint_value;
    bool has_sint_value;
    int64_t sint_value;
    bool has_bool_value;
    bool bool_value;
    pb_extension_t *extensions;
/* @@protoc_insertion_point(struct:vector_tile_Tile_Value) */
} vector_tile_Tile_Value;

/* Default values for struct fields */
extern const uint64_t vector_tile_Tile_Feature_id_default;
extern const vector_tile_Tile_GeomType vector_tile_Tile_Feature_type_default;
extern const uint32_t vector_tile_Tile_Layer_version_default;
extern const uint32_t vector_tile_Tile_Layer_extent_default;

/* Initializer values for message structs */
#define vector_tile_Tile_init_default            {{{NULL}, NULL}, NULL}
#define vector_tile_Tile_Value_init_default      {{{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, NULL}
#define vector_tile_Tile_Feature_init_default    {false, 0ull, {{NULL}, NULL}, false, vector_tile_Tile_GeomType_UNKNOWN, {{NULL}, NULL}}
#define vector_tile_Tile_Layer_init_default      {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 4096u, 1u, NULL}
#define vector_tile_Tile_init_zero               {{{NULL}, NULL}, NULL}
#define vector_tile_Tile_Value_init_zero         {{{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, NULL}
#define vector_tile_Tile_Feature_init_zero       {false, 0, {{NULL}, NULL}, false, _vector_tile_Tile_GeomType_MIN, {{NULL}, NULL}}
#define vector_tile_Tile_Layer_init_zero         {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, 0, NULL}

/* Field tags (for use in manual encoding/decoding) */
#define vector_tile_Tile_layers_tag              3
#define vector_tile_Tile_Feature_id_tag          1
#define vector_tile_Tile_Feature_tags_tag        2
#define vector_tile_Tile_Feature_type_tag        3
#define vector_tile_Tile_Feature_geometry_tag    4
#define vector_tile_Tile_Layer_version_tag       15
#define vector_tile_Tile_Layer_name_tag          1
#define vector_tile_Tile_Layer_features_tag      2
#define vector_tile_Tile_Layer_keys_tag          3
#define vector_tile_Tile_Layer_values_tag        4
#define vector_tile_Tile_Layer_extent_tag        5
#define vector_tile_Tile_Value_string_value_tag  1
#define vector_tile_Tile_Value_float_value_tag   2
#define vector_tile_Tile_Value_double_value_tag  3
#define vector_tile_Tile_Value_int_value_tag     4
#define vector_tile_Tile_Value_uint_value_tag    5
#define vector_tile_Tile_Value_sint_value_tag    6
#define vector_tile_Tile_Value_bool_value_tag    7

/* Struct field encoding specification for nanopb */
extern const pb_field_t vector_tile_Tile_fields[3];
extern const pb_field_t vector_tile_Tile_Value_fields[9];
extern const pb_field_t vector_tile_Tile_Feature_fields[5];
extern const pb_field_t vector_tile_Tile_Layer_fields[8];

/* Maximum encoded size of messages (where known) */
/* vector_tile_Tile_size depends on runtime parameters */
/* vector_tile_Tile_Value_size depends on runtime parameters */
/* vector_tile_Tile_Feature_size depends on runtime parameters */
/* vector_tile_Tile_Layer_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define VECTOR_TILE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
