/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.6 at Mon Nov  2 16:32:49 2020. */

#include "vector_tile.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const uint64_t vector_tile_Tile_Feature_id_default = 0ull;
const vector_tile_Tile_GeomType vector_tile_Tile_Feature_type_default = vector_tile_Tile_GeomType_UNKNOWN;
const uint32_t vector_tile_Tile_Layer_version_default = 1u;
const uint32_t vector_tile_Tile_Layer_extent_default = 4096u;


const pb_field_t vector_tile_Tile_fields[3] = {
    PB_FIELD(  3, MESSAGE , REPEATED, CALLBACK, FIRST, vector_tile_Tile, layers, layers, &vector_tile_Tile_Layer_fields),
    PB_FIELD( 16, EXTENSION, OPTIONAL, CALLBACK, OTHER, vector_tile_Tile, extensions, layers, 0),
    PB_LAST_FIELD
};

const pb_field_t vector_tile_Tile_Value_fields[9] = {
    PB_FIELD(  1, STRING  , OPTIONAL, CALLBACK, FIRST, vector_tile_Tile_Value, string_value, string_value, 0),
    PB_FIELD(  2, FLOAT   , OPTIONAL, STATIC  , OTHER, vector_tile_Tile_Value, float_value, string_value, 0),
    PB_FIELD(  3, DOUBLE  , OPTIONAL, STATIC  , OTHER, vector_tile_Tile_Value, double_value, float_value, 0),
    PB_FIELD(  4, INT64   , OPTIONAL, STATIC  , OTHER, vector_tile_Tile_Value, int_value, double_value, 0),
    PB_FIELD(  5, UINT64  , OPTIONAL, STATIC  , OTHER, vector_tile_Tile_Value, uint_value, int_value, 0),
    PB_FIELD(  6, SINT64  , OPTIONAL, STATIC  , OTHER, vector_tile_Tile_Value, sint_value, uint_value, 0),
    PB_FIELD(  7, BOOL    , OPTIONAL, STATIC  , OTHER, vector_tile_Tile_Value, bool_value, sint_value, 0),
    PB_FIELD(  8, EXTENSION, OPTIONAL, CALLBACK, OTHER, vector_tile_Tile_Value, extensions, bool_value, 0),
    PB_LAST_FIELD
};

const pb_field_t vector_tile_Tile_Feature_fields[5] = {
    PB_FIELD(  1, UINT64  , OPTIONAL, STATIC  , FIRST, vector_tile_Tile_Feature, id, id, &vector_tile_Tile_Feature_id_default),
    PB_FIELD(  2, UINT32  , REPEATED, CALLBACK, OTHER, vector_tile_Tile_Feature, tags, id, 0),
    PB_FIELD(  3, UENUM   , OPTIONAL, STATIC  , OTHER, vector_tile_Tile_Feature, type, tags, &vector_tile_Tile_Feature_type_default),
    PB_FIELD(  4, UINT32  , REPEATED, CALLBACK, OTHER, vector_tile_Tile_Feature, geometry, type, 0),
    PB_LAST_FIELD
};

const pb_field_t vector_tile_Tile_Layer_fields[8] = {
    PB_FIELD(  1, STRING  , REQUIRED, CALLBACK, FIRST, vector_tile_Tile_Layer, name, name, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, vector_tile_Tile_Layer, features, name, &vector_tile_Tile_Feature_fields),
    PB_FIELD(  3, STRING  , REPEATED, CALLBACK, OTHER, vector_tile_Tile_Layer, keys, features, 0),
    PB_FIELD(  4, MESSAGE , REPEATED, CALLBACK, OTHER, vector_tile_Tile_Layer, values, keys, &vector_tile_Tile_Value_fields),
    PB_FIELD(  5, UINT32  , OPTIONAL, STATIC  , OTHER, vector_tile_Tile_Layer, extent, values, &vector_tile_Tile_Layer_extent_default),
    PB_FIELD( 15, UINT32  , REQUIRED, STATIC  , OTHER, vector_tile_Tile_Layer, version, extent, &vector_tile_Tile_Layer_version_default),
    PB_FIELD( 16, EXTENSION, OPTIONAL, CALLBACK, OTHER, vector_tile_Tile_Layer, extensions, version, 0),
    PB_LAST_FIELD
};



/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
